[package]
authors = ["Colin Reeder <vpzomtrrfrt@gmail.com>"]
name = "tokio_discord"
version = "0.1.0"

[dependencies]
futures = "0.1.17"
hyper = "0.11.11"
hyper-tls = "0.1.2"
native-tls = "0.1.4"
quick-error = "1.2.1"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
tokio-core = "0.1.11"
websocket = "0.20.2"
